version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_app
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
      # Autres variables d'environnement nécessaires
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
