FROM nginx:alpine

# Créer le répertoire pour les certificats SSL
RUN mkdir -p /etc/nginx/ssl

# Copier la configuration Nginx dans le conteneur
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Exposer les ports 80 et 443
EXPOSE 80 443

# Commande par défaut pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
