services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '3333:3333'
    volumes:
      - ${APP_DIR}:/app
      - /app/node_modules
  db:
    image: postgres
    container_name: nest_local_pgdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - nest_local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - nest_pgadmin-data:/var/lib/pgadmin

volumes:
  nest_local_pgdata:
  nest_pgadmin-data:
